########### M3 CONFIG ######################
factory_rt_libs:
  - /home/meka/catkin_workspace/install/lib/libkdl_kinematics.so
  - /home/meka/m3controllers/lib/libm3controllers.so

rt_components:
  m3controllers:
#    sin_controller_test: sin_controller
#    dmp_controller_test: dmp_controller
#    vf_controller_test: vf_controller
    m3dynamatics_right_arm_test: m3dynamatics
    vf_force_controller_test: vf_force_controller
#    cart_controller_test: cart_controller
#    torque_controller_test: torque_controller
#    joints_controller_test: joints_controller
